from pandas import DataFrame, read_csv, unique
from numpy import mean, std, array, zeros, shape, where, log10, average
from tqdm import tqdm

from coremstools.assignments.calc.QualityControl import QualityControl
from coremstools.assignments.calc.Dispersity import Dispersity 


class Assignments(QualityControl, Dispersity):


    def __init__(self, sample_df, t_interval = 2):
        
        self.csv_list: list = None         # list of .csv (full path) containing assignment results generated by CoreMS

        self.t_int = t_interval
        self.sample_df = sample_df     # dataframe


    def run_internal_std_qc(self,timerange):
        print(self.sample_df)

        self.sample_df = QualityControl.StandardQC(self.sample_df,timerange)
        








